name: Android Build & Upload

on:
  push:
    branches: [ main ]

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup GraalVM (Gluon)
        uses: gluonhq/setup-graalvm@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Debug Keystore Secrets
        run: |
          if [ -z "${{ secrets.GLUON_ANDROID_KEYSTORE_BASE64 }}" ]; then
            echo "ERROR: GLUON_ANDROID_KEYSTORE_BASE64 no está definido en GitHub Secrets."
            exit 1
          else
            echo "GLUON_ANDROID_KEYSTORE_BASE64 está presente."
          fi

      - name: Decode Android Keystore
        run: |
          echo "${{ secrets.GLUON_ANDROID_KEYSTORE_BASE64 }}" | base64 --decode > android-keystore.jks

      - name: Build Android App
        run: |
          ./mvnw -Pandroid gluonfx:build gluonfx:package
        env:
          GLUON_ANDROID_KEYSTORE_PASSWORD: ${{ secrets.GLUON_ANDROID_KEYSTORE_PASSWORD }}
          GLUON_ANDROID_KEY_ALIAS: ${{ secrets.GLUON_ANDROID_KEY_ALIAS }}
          GLUON_ANDROID_KEY_ALIAS_PASSWORD: ${{ secrets.GLUON_ANDROID_KEY_ALIAS_PASSWORD }}

      - name: Upload APK to Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: android-apk
          path: target/gluonfx/arm64-android/*.apk
