name: iOS Build & Upload to TestFlight

on:
  push:
    branches: [ main ]

jobs:
  build-ios:
    runs-on: macos-14

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup GraalVM (Gluon)
        uses: gluonhq/setup-graalvm@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Import Apple Certificates & Profiles
        uses: Apple-Actions/import-codesign-certs@v1
        with:
          p12-file-base64: ${{ secrets.GLUON_IOS_CERTIFICATES_FILE_BASE64 }}
          p12-password: ${{ secrets.GLUON_IOS_CERTIFICATES_PASSWORD }}

      - name: Download Apple Provisioning Profile
        uses: Apple-Actions/download-provisioning-profiles@v1
        with:
          bundle-id: com.gluonhq.hello.HelloGluonApp
          issuer-id: ${{ secrets.GLUON_IOS_APPSTORE_ISSUER_ID }}
          api-key-id: ${{ secrets.GLUON_IOS_APPSTORE_KEY_ID }}
          api-private-key: ${{ secrets.GLUON_IOS_APPSTORE_PRIVATE_KEY }}

      - name: Set Gluon License
        uses: gluonhq/gluon-build-license@v1
        with:
          gluon-license: ${{ secrets.GLUON_LICENSE }}

      - name: Build iOS App
        run: |
          chmod +x mvnw
          ./mvnw -Pios gluonfx:build gluonfx:package

      - name: Upload App to TestFlight
        uses: Apple-Actions/upload-testflight-build@v1
        with:
          app-path: target/gluonfx/arm64-ios/HelloGluon.ipa
          issuer-id: ${{ secrets.GLUON_IOS_APPSTORE_ISSUER_ID }}
          api-key-id: ${{ secrets.GLUON_IOS_APPSTORE_KEY_ID }}
          api-private-key: ${{ secrets.GLUON_IOS_APPSTORE_PRIVATE_KEY }}

      - name: Cleanup Provisioning Profiles
        if: always()
        run: |
          rm -rf ~/Library/MobileDevice/Provisioning\ Profiles/*
